apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/engine-type: vllm
    llm-d.ai/guide: e-disaggregation
    llm-d.ai/model: Qwen3-VL-235B-A22B-Instruct-FP8
    llm-d.ai/role: encode
  name: e-pd-disaggregation-nvidia-gpu-vllm-encode
  namespace: mayab-diaggr
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: nvidia
      llm-d.ai/engine-type: vllm
      llm-d.ai/guide: e-disaggregation
      llm-d.ai/model: Qwen3-VL-235B-A22B-Instruct-FP8
      llm-d.ai/role: encode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        llm-d.ai/accelerator-variant: gpu
        llm-d.ai/accelerator-vendor: nvidia
        llm-d.ai/engine-type: vllm
        llm-d.ai/guide: e-disaggregation
        llm-d.ai/model: Qwen3-VL-235B-A22B-Instruct-FP8
        llm-d.ai/role: encode
    spec:
      containers:
      - args:
        - Qwen/Qwen3-VL-235B-A22B-Instruct-FP8
        - --disable-access-log-for-endpoints=/health,/metrics,/v1/models
        - --tensor-parallel-size=1
        - --trust-remote-code
        - --mm-processor-cache-gb
        - '20'
        - --mm-encoder-only
        - --enforce-eager
        - --no-enable-prefix-caching
        - --ec-transfer-config
        - '{"ec_connector": "ECCPUConnector", "ec_role": "ec_producer", "ec_connector_extra_config":
          {"ec_cpu_bytes": 10737418240, "ec_enable_nixl": true}}'
        command:
        - vllm
        - serve
        env:
        - name: HF_HOME
          value: /model-cache
        - name: VLLM_EC_SIDE_CHANNEL_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: VLLM_EC_SIDE_CHANNEL_PORT
          value: '5610'
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: llm-d-hf-token
        - name: USER
          value: llm-d
        - name: VLLM_LOGGING_LEVEL
          value: INFO
        image: docker.io/vllm/vllm-openai@sha256:ed3c505d2cf4b62b0ca8d0b87591bcb6fbff2a3abcc6d25732343e19b4d74f09
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: modelserver
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: modelserver
        ports:
        - containerPort: 8000
          name: modelserver
          protocol: TCP
        - containerPort: 5610
          name: ec-nixl
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/models
            port: modelserver
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: '8'
            memory: 256Gi
            nvidia.com/gpu: '1'
            rdma/ib: '1'
          requests:
            cpu: '8'
            memory: 64Gi
            nvidia.com/gpu: '1'
            rdma/ib: '1'
        startupProbe:
          failureThreshold: 120
          httpGet:
            path: /v1/models
            port: modelserver
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /.cache
          name: torch-compile-cache
        - mountPath: /.triton
          name: triton-cache
        - mountPath: /.config
          name: config-cache
        - name: model-cache
          mountPath: /model-cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: e-pd-disaggregation-nvidia-gpu-vllm-sa
      serviceAccountName: e-pd-disaggregation-nvidia-gpu-vllm-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 16Gi
        name: shm
      - emptyDir: {}
        name: torch-compile-cache
      - emptyDir: {}
        name: triton-cache
      - emptyDir: {}
        name: config-cache
      - name: model-cache
        persistentVolumeClaim:
          claimName: e-pd-disaggregation-nvidia-gpu-vllm-model-cache
      nodeSelector:
        kubernetes.io/hostname: g13bc90
